inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/StringLiterals:
  Include:
    - "db/**/*"
