<% require "dotenv"; Dotenv.load(".env.production") %>

service: finb

image: <%= ENV["KAMAL_IMAGE_NAME"] %>

servers:
  web:
    hosts:
      - <%= ENV["KAMAL_HOST"] %>

proxy:
  ssl: true
  host: <%= ENV["KAMAL_HOST"] %>

registry:
  username: <%= ENV["KAMAL_REGISTRY_USERNAME"] %>
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

env:
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: app

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
