service: finb

image: <%= ENV['KAMAL_IMAGE_NAME'] %>

servers:
  web:
    hosts:
      - <%= ENV['KAMAL_SERVER_IP'] %>
    labels:
        traefik.http.routers.finb-beta.entrypoints: websecure
        traefik.http.routers.finb-beta.rule: Host(`<%= ENV['LETS_ENCRYPT_DOMAIN'] %>`)
        traefik.http.routers.finb-beta.tls.certresolver: letsencrypt

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  multiarch: false

ssh:
  user: app

env:
  secret:
    - SECRET_KEY_BASE

volumes:
  - "storage:/rails/storage"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    accesslog: true
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "<%= ENV['LETS_ENCRYPT_EMAIL'] %>"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

healthcheck:
  cord: false
