name: Deploy

on:
  push:
    branches:
      - production

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
    runs-on: ubuntu-24.04-arm

    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

      - name: Set Tag
        id: tag
        run: |
          echo "tag=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64/v8
          push: true
          labels: |
            "service=finb"
          tags: |
            "${{ secrets.KAMAL_IMAGE_NAME }}:latest"
            "${{ secrets.KAMAL_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Deploy command
        run: bundle exec kamal deploy --skip-push
        env:
          RAILS_MASTER_KEY: ${{ secrets.PRODUCTION_RAILS_MASTER_KEY }}
          KAMAL_IMAGE_NAME: ${{ secrets.KAMAL_IMAGE_NAME }}
          KAMAL_HOST: ${{ secrets.KAMAL_HOST }}
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          KAMAL_SSH_USER: ${{ secrets.KAMAL_SSH_USER }}
          HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
